name: bybey
favicon: null
layout_spectrum: 0.47264096210710704
typography_spectrum: 0.5710590491071343
title: bybey pattern design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9dc1fa'
    - '#4ab360'
    - '#006527'
    - '#a93c2a'
  brandStrength: 0.0699619515798986
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.642137301620096
purpose: []
