name: bybey
favicon: null
layout_spectrum: 0.47264096210710704
typography_spectrum: 0.5710590491071343
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.0699619515798986
  lightness: 0.563822562340647
  saturation: 0.5542230485007167
  rhythmicContrast: 0.642137301620096
purpose: []
